// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'pref-description'
  | 'pref-disable-underlines'
  | 'pref-help'
  | 'pref-suggestion-count'
  | 'pref-suggestion-count-hint'
  | 'pref-title'
  | 'prefs-title'
  | 'spellcheck-add-to-dictionary'
  | 'spellcheck-menu-label'
  | 'spellcheck-no-suggestions'
  | 'startup-begin'
  | 'startup-finish';
